auto_reload_config 0.1
allow_remote_control yes

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 18.0
#END_KITTY_FONTS

# WINDOW DECORATIONS
hide_window_decorations titlebar-only

# APPERANCE
background_opacity 0.8
background_blur 45

copy_on_select yes
tab_bar_style separator
window_border_width 0.5
window_margin_width 3
window_padding_width 3
window_border_radius 15
enabled_layouts grid

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

# KEYBINDINGS
map --allow-fallback=shifted,ascii cmd+d new_window
map --allow-fallback=shifted,ascii cmd+w remote_control_script close_window_or_tab.py
map --allow-fallback=shifted,ascii ctrl+shift+alt+[ previous_tab
map --allow-fallback=shifted,ascii ctrl+shift+alt+] next_tab
map --allow-fallback=shifted,ascii cmd+ctrl+shift+alt+[ previous_window
map --allow-fallback=shifted,ascii cmd+ctrl+shift+alt+] next_window


