#!/usr/bin/env sh

# config
yabai -m config mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_topmost off \
  window_shadow float \
  window_opacity on \
  active_window_opacity 1.0 \
  normal_window_opacity 0.50 \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_follows_focus on \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 15 \
  layout bsp

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^UTM$" manage=off
yabai -m rule --add app="^1Password$" manage=off sticky=off

borders &
