import = [
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity=0.8
blur=true

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 24

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },
  { key = "Right", mods = "Command", chars =  "\u001bOF" },
  { key = "Back",  mods = "Command", chars = "\u0015"    },
]

